Task 1.1
LeraPazgert/itStep pull request #2
Opened 2021-11-15 12:40 UTC by LeraPazgert

2021-11-15 20:34 UTC, itstep-mog requested changes
В целом работа очень понравилась. Сделано красиво и со вкусом. Делай исправления по замечаниям и объединяй ветки.

2021-11-15 20:34 UTC, itstep-mog commented on Task 1/Catalog.html
> +            </h3>
Все же это не заголовок a` div `или просто `<a>` со стилями, т.к. заголовок подразумевает под собой наименование раздела или категории. В данном месте он не целесообразен

2021-11-15 20:34 UTC, itstep-mog commented on Task 1/Catalog.html
> +            </h3>
Тот же заголовок , который нужно заменить или убрать оставив только тег `<a>`

2021-11-15 20:34 UTC, itstep-mog commented on Task 1/Catalog.html
> +            </h3>
Тот же заголовок , который нужно заменить или убрать оставив только тег `<a>`

2021-11-15 20:34 UTC, itstep-mog commented on Task 1/Catalog.html
> +            <h2 style="color:rgb(192, 42, 42); text-align: center;"><i>Tour to New York</i></h2>
В строке заголовок будет вида `<h3>`, т.к. он находится в разделе с объявленным заголовком `<h2>`. Вложенность тут будет влиять на это и важность самого заголовка. Важный момент - заголовки придают важность тексту, а не просто задают жирный шрифт. Для двух других блоков тоже самое (уже не буду комментировать их) строки 32 и 40

2021-11-15 20:34 UTC, itstep-mog commented on Task 1/Contacts.html
> +            <p>aroundtheworld@gmail.com</p>
Тут имеет смысл сделать `<a href="mailto:aroundtheworld@gmail.com">aroundtheworld@gmail.com</a>`

2021-11-16 13:07 UTC, LeraPazgert commented on Task 1/Catalog.html
> +            <h2 style="color:rgb(192, 42, 42); text-align: center;"><i>Tour to New York</i></h2>
Не очень поняла про вложенность, у меня h2 - это просто название страницы. А следующие заголовки h2 - это названия туров. Я точно также акцентирую на них внимание. И они не входят в раздел с объявленным заголовком <h2>. Он объявлен и сразу закрыт. Я поменяла на h3, но хочу точно понять, надо ли это

2021-11-18 12:07 UTC, merged